export const GET_PROJECT = 'GET_PROJECT';
export const GET_MEETING_LIST = 'GET_MEETING_LIST';
export const CLOSE_PREVIEW = 'CLOSE_PREVIEW';
export const OPEN_PREVIEW = 'OPEN_PREVIEW';
export const TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN';
export const DISPLAY_MEETING_DETAIL = 'DISPLAY_MEETING_DETAIL';
